### ISSUE TITLE
DataLoader() takes no arguments

### ISSUE THREAD

**Issue by AkshitaB** [allenai/allennlp-guide-examples#13]
I encounter the following error when running the `quick_start/evaluate.py` demo evaluation on my machine.

```
Traceback (most recent call last):
  File "quick_start/evaluate.py", line 181, in <module>
    model, dataset_reader = run_training_loop()
  File "quick_start/evaluate.py", line 162, in run_training_loop
    train_loader, dev_loader = build_data_loaders(train_data, dev_data)
  File "quick_start/evaluate.py", line 116, in build_data_loaders
    train_loader = DataLoader(train_data, batch_size=8, shuffle=True)
TypeError: DataLoader() takes no arguments
```

I believe this is due to generalizing the DataLoader. Possibly `PyTorchDataLoader` should be used instead. Similar code also exists in `quick_start/train.py` and `quick_start/predict.py`.

**Comment by matt-gardner** [comment]
Yes, you're right, this needs to be updated when we update to 1.1.  Maybe we should pin the requirements in this repo to be v1.0?

**Comment by idjotherwise** [comment]
I had the same problem when running the scripts locally - downgrading from v1.1 to v1.0 fixed it.

**Comment by YYGe01** [comment]
it work:

from allennlp.data import PyTorchDataLoader

train_loader = PyTorchDataLoader(train_data, batch_size=8, shuffle=True)
dev_loader = PyTorchDataLoader(dev_data, batch_size=8, shuffle=False)

**Comment by AslanDevbrat** [comment]
> it work:
> 
> from allennlp.data import PyTorchDataLoader
> 
> train_loader = PyTorchDataLoader(train_data, batch_size=8, shuffle=True)
> dev_loader = PyTorchDataLoader(dev_data, batch_size=8, shuffle=False)

This code really worked for me, Just replace every DataLoader with PyTorchDataloaderLoader, and its done!
Mine AllenNLP version is 1.2.2
